### ISSUE TITLE
Enhance gw_releases.json

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-vmware-visualisation#46]
**To include in the json**:
- Submodule sdk-rebuild-eval which is a submodule of k8-rebuild-rest-api
- Submodule release tag
- GW-Releases repo
- "Release body"
![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/367fa491-bafc-44d2-b896-62fc93e4baac)

**Comment by baker371** [comment]
@chrisdiao the body is captured, it is just renamed "release_name" in the json file, if you compere this side by side you will be able to see what I am talking about

**Comment by baker371** [comment]
@chrisdiao the body is captured, it is just renamed "release_name" in the json file, if you compere this side by side you will be able to see what I am talking about

**Comment by chrisdiao** [comment]
@baker371 
For instance in GW-proxy  release tag v0.5.1 this should be the release body 
![image](https://user-images.githubusercontent.com/68153062/108547373-5b704280-7325-11eb-9a1f-a5eeb6047035.png)

**Comment by baker371** [comment]
@chrisdiao I see your point but if you check the API, the field comes up empty for GW-proxy, yet shows up for aws-jmeter-test-engine/releases. Take a look and advise.
![re2](https://user-images.githubusercontent.com/8102313/108555522-9ca52a00-7306-11eb-834f-eda517205fa5.PNG)
![re3](https://user-images.githubusercontent.com/8102313/108555541-a333a180-7306-11eb-810b-4b25343ad5a8.PNG)

**Comment by chrisdiao** [comment]
@baker371 , we can use the commits API for this
![image](https://user-images.githubusercontent.com/68153062/108708689-bfc11b00-754c-11eb-9b30-9465877aa0f2.png)
